### ISSUE TITLE
Question: IntelliSense warnings I don't understand

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#10]
You may not be able to help here, but I have the following mapping line defined:

```
    MapAxis2(xbc, XBC::TRIGGER, AllLayers, {-0.8, 0.8},
             {new ActionButtonPress(vjoy, SCJ::FireGroup1),
              new ActionChain({new ActionButtonRelease(vjoy, SCJ::FireGroup1),
                               new ActionButtonRelease(vjoy, SCJ::FireGroup2)}),
              new ActionButtonPress(vjoy, SCJ::FireGroup2)});
```

The code compiles just fine and operates as I would expect it to for the above mapping (ignore the fact that I know if I hold both triggers, it won't fire either weapon because of the summing, I'm just experimenting with ways to utilize the single combined trigger axis). However, in my editor (Visual Studio Code) the IntelliSense checking is highlighting "MapAxis2" and "ActionChain" with the following warnings:

For MapAxis2:
```
no instance of overloaded function "Profile::MapAxis2" matches the argument list -- argument types are: (EnhancedJoystick *, const uint, LayersCombo, {...}, {...})
MapAxis2
```

For ActionChain:
```
no instance of constructor "ActionChain::ActionChain" matches the argument list -- argument types are: ({...})
class ActionChain
```

Everything else in my code is checking fine and working as expected, but when I use MapAxis2, it complains.

If I change the mapping to something stupid like this:
```
    MapAxis2(xbc, XBC::TRIGGER, AllLayers, 2, 0);
```
or this:
```
    MapAxis2(xbc, XBC::TRIGGER, AllLayers, 2, nullptr);
```
It no longer complains. However, if I use this:
```
MapAxis2(xbc, XBC::TRIGGER, AllLayers, {-0.8, 0.8}, nullptr);
```
It complains again with the same thing. It's like it's not understanding the `{}` notation as a vector, I guess. 

Any clues? I'll keep digging, as it could just be something in my editor setup that is wrong or something. I realize this isn't your problem, but was wondering if there was something about their definitions that would be tripping up an IDE system like this.

**Comment by robert914** [comment]
After adding some explicit typing for the vectors, the following no longer complains with warnings in VSCode:
```
    MapAxis2(xbc, XBC::TRIGGER, AllLayers, std::vector<float>({-0.8f, 0.8f}),
             std::vector<AbstractAction *>(
                 {new ActionButtonPress(vjoy, SCJ::FireGroup1),
                  new ActionChain(std::vector<AbstractAction *>(
                      {new ActionButtonRelease(vjoy, SCJ::FireGroup1),
                       new ActionButtonRelease(vjoy, SCJ::FireGroup2)})),
                  new ActionButtonPress(vjoy, SCJ::FireGroup2)}));
```
And it compiles and runs fine. I guess I'm not quite sure why it can't seem to handle the use of just the `{...}` in the arguments vs. having to explicitly create them as `std::vector` objects.

If you have any thoughts, I'd appreciate it. I guess I can deal with the extra explicit declarations so that the coding IntelliSense on-the-fly checking works, as it's super helpful. So if there is nothing you know is causing this on your end, or if you know a better way to do this, you can just close this issue.

**Comment by robert914** [comment]
I'm closing this. This warning issue only occurs when I'm doing the development on my Mac vs directly in Windows. So it's something I have setup on the Mac side that's not picking up proper libraries for the checks. VSCode works correctly with the original code when used on Windows.

**Comment by 3noix** [comment]
I have no idea at all. Sorry.
