### ISSUE TITLE
Question: What is difference in usage of upper/lower dead zones vs zoom?

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#12]
What is the difference in curve behavior between these two lines?
```
twcs->setSCurve(TWCS::JOYX, 0.02f, 0.15f, 0.02f, 3.0f, 0.0f);
```
```
twcs->setSCurve(TWCS::JOYX, 0.0f, 0.15f, 0.0f, 3.0f, 0.4f);
```
If I use the AxisCurves.exe to view these parameter setups, the curves looks pretty much exactly the same (to the naked eye, and even comparing exact screenshots it looks almost exactly the same). My main question is whether there is some other behavior difference between using the "zoom" value vs using lower/upper dead zone values? I'm trying to understand what "zoom" is really doing vs. the dead zones on the ends.

Thanks!

BTW - is this the best way to ask you questions about this, but submitting issue tickets? It's not really an issue, but I can't find any other way to ask general questions (other than post on the Spectrum board, but these questions are not SC specific).

**Comment by 3noix** [comment]
It is equivalent in this case, but if you add trims or use negative values for zoom, you will see that you cannot do the same using only other parameters. The zoom value applies a factor (1.41^zoom) on the input before applying the curve function... it is quite simplified, if you want to see exactly how the curve is computed, you can see it in "AxesCurves/CODE/CURVES/SCurveGUI.cpp/SCurveGUI::run"

**Comment by 3noix** [comment]
And about the way to ask questions, like you do currently is ok, just keep your prefixes "Question:", ...

In fact, after a quick search on Google, it seems there is no better way to do it on GitHub, and that this issue is already well discussed: "GitHub ask question" on Google and https://gist.github.com/ccannon94/4980dc78456cb7a7ab38028e933cb01e

**Comment by robert914** [comment]
Ok, thanks. I suspected as much, but had not thought of using a negative zoom.  I did end up looking at the equations in SCurve::run to see what it was doing. Still not sure what the use for zoom is, as I've not had anything that I can tell would need it. 

Thanks! I'll keep prefixing my issues then, and use the "Question:" for stuff that doesn't require fixes/changes. 👍

**Comment by 3noix** [comment]
In fact for J and S curves I just made a copy-paste from Thrustmaster curves :-)
