### ISSUE TITLE
Question: What is the difference between DoAction and setButton?

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#14]
So if I have the following map with callback:

```
    Map(xbc, ControlType::Button, XBC::SHOULDERR, AllLayers,
        new TriggerButtonChange{},
        new ActionCallback([this]() { this->fireAll(); }));
```

What is the difference between my callback doing this:
```
void Profile::fireAll()
{
    if (xbc->buttonPressed(XBC::SHOULDERR))
    {
        DoAction(new ActionButtonPress{vjoy, VJOY::DX1});
        DoAction(new ActionButtonPress{vjoy, VJOY::DX2});
    }
    else
    {
        DoAction(new ActionButtonRelease{vjoy, VJOY::DX1});
        DoAction(new ActionButtonRelease{vjoy, VJOY::DX2});
    }
}
```

versus doing this:
```
void Profile::fireAll()
{
    if (xbc->buttonPressed(XBC::SHOULDERR))
    {
        vjoy->setButton(VJOY::DX1, true);
        vjoy->setButton(VJOY::DX2, true);
    }
    else
    {
        vjoy->setButton(VJOY::DX1, false);
        vjoy->setButton(VJOY::DX2, false);
    }
}
```

My intent is that when I hold down button XBC::SHOULDERR, that both buttons VJOY::DX1 and VJOY::DX2 on my vJoy device are also held down, and subsequently when releasing  XBC::SHOULDERR the vJoy device buttons are then released.

Don't the above result in the exact same behavior? Is one better than the other? Is there a better way to map one real joystick button to multiple virtual joystick buttons?

The documentation does not make this very clear, as it states:

> The function "DoAction" of the class AbstractProfile is useful to perform an action, from a callback from example. It is quite equivalent to the "ActKey" function of Thrustmaster TARGET but really more powerful as it can perform any action. But for some actions, there is no need to use DoAction. Here is an example:
```
DoAction(new ActionButtonPress{vj1, VJOY::DX1});
vj1->setButton(VJOY::DX1, true);
```
> By default the action is deleted after performed. If you don't want to delete it, provide false as a second argument.

But I don't understand the last comment about the "action is deleted after performed". It's not clear what the different between the two ways is. The behavior seems to work the same in my tests.

Thanks!

**Comment by 3noix** [comment]
Your 2 ways are equivalent, but DoAction is useless in this case: you can do simpler with:
```
MapButton(xbc, ControlType::Button, XBC::SHOULDERR, AllLayers, vjoy, VJOY::DX1);
MapButton(xbc, ControlType::Button, XBC::SHOULDERR, AllLayers, vjoy, VJOY::DX2);
```

In fact, contrary to Thrustmaster, when you add a mapping to a real button (or axis or pov) that is already mapped, the previous mapping is not removed. If you want to remove it, you need to call one of the "Unmap" function. It is a choice I have made... another way would be to add an argument "unmapExistingMappingsForThisButton" at the end of each "Map" function with a default value.

It is indeed something very important I did not tell in the documentation. I will add it in §12.

**Comment by robert914** [comment]
Oh! Nice, I did not notice that multiple mappings to the same button were retained. That does make one to many button mappings easier. Thanks!

**Comment by 3noix** [comment]
First with DoAction you can only perform an action (scoop!!), which allows you to:
- generate vJoy events (buttons, axes, povs)
- keyboard events
- execution of a function
- or all of them (with the chains or sequences)

But the real interest of it is that you can delay these events: with it you can for example send a pulse on a button from a callback. With only setButton, it is not possible (or you will have to create timers, or something equivalent).

**Comment by 3noix** [comment]
I use it in my current Star Citizen profile:
```
auto powerPreset1Toggle = [this]() {if (!tmwt->buttonPressed(TMWT::LDGH)) DoAction(new ActionButtonPulse{vj1,SC::PowerPreset1Toggle,ncPulse});};
Map(tmwt, ControlType::Button, TMWT::EACON,   AllLayers, new TriggerButtonChange{}, new ActionCallback{powerPreset1Toggle});
```

I use the "LDGH" button as an "inhibition button" for toggles that are mapped to real switches on my throttle... I have to do this to solve desync issues... there will be no problem anymore once CIG will provide a "set" and "reset" binding for each "toggle" binding.

**Comment by robert914** [comment]
Ok, that makes sense. I was wondering why you had those coded like that (I don't have a Warthog, so I didn't know how some of the buttons/switches worked). Although, I've been tempted to get a Warthog for so long. :)

**Comment by 3noix** [comment]
And about the deletion of the action: I mean the deletion of the Action object, to avoid a memory leak, nothing more.

To be exact, a vector of VirtualEvents is created when AbstractAction::generateEvents is called on one action. Then this list of events is added to the VirtualEventsQueue of the profile. Each event has a delay that is decremented at each time step. Once it reaches 0 the event is sent (to vJoy, keyboard, or the function is executed) and the VirtualEvent is removed from the queue.

When using DoAction, the action is deleted just after calling generateEvents, there is even no need to wait for the events to be sent!
```
void AbstractProfile::DoAction(AbstractAction *action, bool deleteWhenDone)
{
	Q_ASSERT(action);
	m_eventsQueue.postEvents(action->generateEvents());
	if (deleteWhenDone) {delete action;}
}
```

**Comment by 3noix** [comment]
To better explain you the issue, here is the simpler situation to understand: when you enter the seat of your ship, and let's say everything is off on your ship. Then you press "flight ready". Whatever the position of your "weapons switch" (on the throttle) the weapons will turn on: you can generate a desynchro. The better would be to have an init function as below, but to do so CIG has to provide "on" and "off" binding for each toggle. Sim games do it!
```
Map(tmwt, TMWT::LDGH, AllLayers,
	new TriggerButtonPress{},
	new ActionCallback{[this](){this->initButton();}}
);

void Profile::initButton()
{
	if (tmwt->buttonPressed(TMWT::EACON)) {DoAction(new ActionButtonPulse{vj1, SC::SetWeaponsPowerOn});}
	else                                  {DoAction(new ActionButtonPulse{vj1, SC::SetWeaponsPowerOff});}
}
```

But it can be more dangerous: I was at high speed and low altitude above Yela and I was playing with power (just for test). I added 1 time power to weapons, and another one to shields. It sets the engines power to 0, and even after resetting power, the engines wre not back: they have been switched off! No more time to react, I just crashed on the ground :-)

**Comment by robert914** [comment]
Yes, makes perfect sense. :-)  Thanks for the clarification!
