### ISSUE TITLE
Compilation warnings - are they a problem?

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#2]
I am able to successfully compile UJPS using the bat file and run it. However, when I load up a profile and click "compile", I see these warnings during compilation:

`In file included from ..\..\StaticLibs\INCLUDES\VirtualJoysticks/VirtualJoystick.h:10:0,
                 from ..\..\StaticLibs\INCLUDES\UjpsCore/ACTIONS/ActionButtonToggle.h:6,
                 from ..\..\StaticLibs\INCLUDES\UjpsCore/ACTIONS/Actions.h:10,
                 from CODE\Profile.cpp:4:
..\..\StaticLibs\INCLUDES\VirtualJoysticks/vJoyModifiedInterface/public.h:58:31: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define NTDEVICE_NAME_STRING  "\\Device\\"DEVICENAME_STRING
                               ^
..\..\StaticLibs\INCLUDES\VirtualJoysticks/vJoyModifiedInterface/public.h:59:31: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define SYMBOLIC_NAME_STRING  "\\DosDevices\\"DEVICENAME_STRING
                               ^
..\..\StaticLibs\INCLUDES\VirtualJoysticks/vJoyModifiedInterface/public.h:60:26: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define DOS_FILE_NAME    "\\\\.\\"DEVICENAME_STRING
                          ^`

And the last line reads:

`Compilation failed or finished with warning(s) !`

However, it seems to let me click "Run" on the profile. Now, I can't verify that it's actually running yet, since your sample profile is for devices I don't actually have, so I need to go write one of my own to actually test, but I'm trying to make sure I have everything setup properly.

The above warnings also appear during compilation using build_UJPS.bat, but it seems to keep going. 

Should I be concerned about these warnings?

**Comment by robert914** [comment]
Here is the complete log output of a compile of your sample 3.1.4 Star Citizen setup:

`Command : cd D:/Source/UJPS/Build/Profiles/StarCitizen_3.1.4_v5
Command : qmake StarCitizen_314_v5.pro
Command : mingw32-make release
C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile.Release
mingw32-make[1]: Entering directory 'D:/Source/UJPS/Build/Profiles/StarCitizen_3.1.4_v5'
g++ -c -fno-keep-inline-dllexport -O2 -std=gnu++11 -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -I..\..\StaticLibs\INCLUDES\QtGameControllerModif -I..\..\StaticLibs\INCLUDES\Other -I..\..\StaticLibs\INCLUDES\VirtualJoysticks -I..\..\StaticLibs\INCLUDES\RealJoysticks -I..\..\StaticLibs\INCLUDES\UjpsCore -I..\..\ControllersPlugins\INCLUDES -IC:\Qt\5.11.0\mingw53_32\include -IC:\Qt\5.11.0\mingw53_32\include\QtGui -IC:\Qt\5.11.0\mingw53_32\include\QtANGLE -IC:\Qt\5.11.0\mingw53_32\include\QtCore -Irelease\moc -IC:\Qt\5.11.0\mingw53_32\mkspecs\win32-g++  -o release\objects\Profile.o CODE\Profile.cpp
In file included from ..\..\StaticLibs\INCLUDES\VirtualJoysticks/VirtualJoystick.h:10:0,
                 from ..\..\StaticLibs\INCLUDES\UjpsCore/ACTIONS/ActionButtonToggle.h:6,
                 from ..\..\StaticLibs\INCLUDES\UjpsCore/ACTIONS/Actions.h:10,
                 from CODE\Profile.cpp:4:
..\..\StaticLibs\INCLUDES\VirtualJoysticks/vJoyModifiedInterface/public.h:58:31: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define NTDEVICE_NAME_STRING  "\\Device\\"DEVICENAME_STRING
                               ^
..\..\StaticLibs\INCLUDES\VirtualJoysticks/vJoyModifiedInterface/public.h:59:31: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define SYMBOLIC_NAME_STRING  "\\DosDevices\\"DEVICENAME_STRING
                               ^
..\..\StaticLibs\INCLUDES\VirtualJoysticks/vJoyModifiedInterface/public.h:60:26: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define DOS_FILE_NAME    "\\\\.\\"DEVICENAME_STRING
                          ^
g++ -fno-keep-inline-dllexport -O2 -std=gnu++11 -Wall -W -Wextra -dM -E -o release\moc\moc_predefs.h C:\Qt\5.11.0\mingw53_32\mkspecs\features\data\dummy.cpp
C:\Qt\5.11.0\mingw53_32\bin\moc.exe -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB --include release/moc/moc_predefs.h -IC:/Qt/5.11.0/mingw53_32/mkspecs/win32-g++ -ID:/Source/UJPS/Build/Profiles/StarCitizen_3.1.4_v5 -ID:/Source/UJPS/Build/Profiles/StarCitizen_3.1.4_v5 -ID:/Source/UJPS/Build/StaticLibs/INCLUDES/QtGameControllerModif -ID:/Source/UJPS/Build/StaticLibs/INCLUDES/Other -ID:/Source/UJPS/Build/StaticLibs/INCLUDES/VirtualJoysticks -ID:/Source/UJPS/Build/StaticLibs/INCLUDES/RealJoysticks -ID:/Source/UJPS/Build/StaticLibs/INCLUDES/UjpsCore -ID:/Source/UJPS/Build/ControllersPlugins/INCLUDES -IC:/Qt/5.11.0/mingw53_32/include -IC:/Qt/5.11.0/mingw53_32/include/QtGui -IC:/Qt/5.11.0/mingw53_32/include/QtANGLE -IC:/Qt/5.11.0/mingw53_32/include/QtCore -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward CODE\Profile.h -o release\moc\moc_Profile.cpp
g++ -c -fno-keep-inline-dllexport -O2 -std=gnu++11 -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -I..\..\StaticLibs\INCLUDES\QtGameControllerModif -I..\..\StaticLibs\INCLUDES\Other -I..\..\StaticLibs\INCLUDES\VirtualJoysticks -I..\..\StaticLibs\INCLUDES\RealJoysticks -I..\..\StaticLibs\INCLUDES\UjpsCore -I..\..\ControllersPlugins\INCLUDES -IC:\Qt\5.11.0\mingw53_32\include -IC:\Qt\5.11.0\mingw53_32\include\QtGui -IC:\Qt\5.11.0\mingw53_32\include\QtANGLE -IC:\Qt\5.11.0\mingw53_32\include\QtCore -Irelease\moc -IC:\Qt\5.11.0\mingw53_32\mkspecs\win32-g++  -o release\objects\moc_Profile.o release\moc\moc_Profile.cpp
g++ -Wl,-s -shared -Wl,-subsystem,windows -mthreads -Wl,--out-implib,release\libStarCitizen_314_v5.a -o release\StarCitizen_314_v5.dll release/objects/Profile.o release/objects/moc_Profile.o  ..\..\StaticLibs\SOURCES\QtGameControllerModif\release\libQtGameControllerModif.a ..\..\StaticLibs\SOURCES\RealJoysticks\release\librealJoysticks.a ..\..\StaticLibs\SOURCES\VirtualJoysticks\release\libvirtualJoysticks.a ..\..\StaticLibs\SOURCES\UjpsCore\release\libujpsCore.a ..\..\vJoy218SDK-291116\SDK\lib\vJoyInterface.lib -LC:\Qt\5.11.0\mingw53_32\lib C:\Qt\5.11.0\mingw53_32\lib\libQt5Gui.a C:\Qt\5.11.0\mingw53_32\lib\libQt5Core.a
mingw32-make[1]: Leaving directory 'D:/Source/UJPS/Build/Profiles/StarCitizen_3.1.4_v5'
Compilation failed or finished with warning(s) !
`

**Comment by robert914** [comment]
Here are some other stray compile warnings during the build process (not during profile compile):

`CODE\MainWindow.cpp: In member function 'void MainWindow::slotRunOneLoop()':
CODE\MainWindow.cpp:160:58: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (ch.type == ControlType::Axis && ch.numButtonOrAxis == m_axis)
                                                          ^`

`CODE\QGameController.cpp: In member function 'float QGameController::axisValue(uint)':
CODE\QGameController.cpp:184:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (axis >= d->AxesValues.size()) {return 0.0f;}
           ^
CODE\QGameController.cpp: In member function 'bool QGameController::buttonValue(uint)':
CODE\QGameController.cpp:191:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (button >= d->ButtonsValues.size()) {return false;}
             ^
CODE\QGameController.cpp: In member function 'float QGameController::povValue(uint)':
CODE\QGameController.cpp:198:10: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (pov >= d->PovsValues.size()) {return false;}
          ^`

`CODE\QGameController_win.cpp: In constructor 'QGameControllerPrivate::QGameControllerPrivate(uint, QGameController*)':
CODE\QGameController_win.cpp:70:34: warning: missing initializer for member 'DIJOYCONFIG::guidInstance' [-Wmissing-field-initializers]
  DIJOYCONFIG PreferredJoyCfg = {0};
                                  ^`

This one is similar to the profile warning (same cause):

`In file included from ..\StaticLibs\INCLUDES\VirtualJoysticks/VirtualJoystick.h:10:0,
                 from CODE\SETTINGS\VJoySettingsWidget.cpp:5:
..\StaticLibs\INCLUDES\VirtualJoysticks/vJoyModifiedInterface/public.h:58:31: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define NTDEVICE_NAME_STRING  "\\Device\\"DEVICENAME_STRING
                               ^
..\StaticLibs\INCLUDES\VirtualJoysticks/vJoyModifiedInterface/public.h:59:31: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define SYMBOLIC_NAME_STRING  "\\DosDevices\\"DEVICENAME_STRING
                               ^
..\StaticLibs\INCLUDES\VirtualJoysticks/vJoyModifiedInterface/public.h:60:26: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define DOS_FILE_NAME    "\\\\.\\"DEVICENAME_STRING
                          ^`

**Comment by 3noix** [comment]
No, don't worry, all is fine. There are 3 issues here:

1. the lines 58, 59 and 60 of StaticLibs/INCLUDES/VirtualJoysticks/vJoyModifiedInterface/public.h. It is a C header file from vJoy that I already modified to remove some other warnings. I was not sure about the modification to do for this one so I did not tackle it yet. It is included in the VirtualJoystick class, and consequently in many places that is why there are many such warnings.

2. The second one is 3 comparisons between ints and unsigned ints... same, I don't know how to tackle it at first glance and I just thought I will tackle it later. In fact the uint is an index (of a button, an axis or a pov) that must be a uint, and it is compared to the size of the container (the number of buttons / axes / povs) which is an int. And if I try to convert it to a uint, it should generate another warning... why sizes are not uint !?! I will try to do what I can do, but there is really no reason to worry.

3. In QGameController_win.cpp at line 70, a structure of type "DIJOYCONFIG" (from Windows DirectInput library) is declared, and only the first member of the structure is initialized, which generates this warning. Providing any initial value for other members should remove the warning with no side effect. It will be an easy fix.

When you compile a profile you should see only warnings of type 1. And if you use the compiler interface tool I provide in the UJPS main app, you should indeed see "Compilation failed or finished with warning(s) !" at the end. But if the compilation went correctly until the end, it is ok, it is just because what I coded is not smart enough to do the difference between an error and a warning: the QtCompilationProcess object send this message if the compilation process sent anything on the standard error stream std::cerr, which receives both warning and error messages. To make the difference, I think it will be necessary to interpret the compilation messages... so not so easy

**Comment by robert914** [comment]
Ok, that’s basically what I figured was happening. I will ignore them for now then, thanks!
You can close this issue if you want.

**Comment by 3noix** [comment]
I made modifications in this commit (https://github.com/3noix/UJPS/commit/eda1c7f5b72cbbf79036c0537a69f64281de0e68) to remove all these compilation warnings.

**Comment by robert914** [comment]
Awesome! Thanks for cleaning these up!
