### ISSUE TITLE
Request: Add joystick name to plugin header file for use in profile code

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#5]
Currently, we have to do the following in our profile code:

```
xb1 = this->registerRealJoystick("Controller (XBOX 360 For Windows)");
```

It would be nice if that string (which is specific to the plugin) was provided in the header we include above:

```
#include "MicrosoftXbox360Controller.h"
```

Maybe something like:

```
#ifndef INSIDE_PLUGIN
namespace MicrosoftXbox360Controller
#else
namespace MicrosoftXbox360Controller_
#endif
{
	const QString DESCRIPTION = "Controller (XBOX 360 For Windows)";

	const uint BA = 0;	// button A
	const uint BB = 1;	// button B
	const uint BX = 2;	// button X
	const uint BY = 3;	// button Y
```

Then we can do something like:

```
#include "MicrosoftXbox360Controller.h"
namespace XB360 = MicrosoftXbox360Controller;

...

  xb1 = this->registerRealJoystick(XB360::DESCRIPTION);
```

And not have to know the exact string to use to pick up the joystick. You could also use that constant in your code where you have that string placed as well. Seems like this would be easier on users to not have to know the exact string to use (i.e. would need to look it up in your code to find it).

Unless I'm totally missing something here? I was unable to access the "description()" method like this:

`xb1 = this->registerRealJoystick(MicrosoftXbox360Controller::description());`

Because it's an instance method, not a class method. Maybe just make that a class method, and the problem is also solved?

Thoughts?

Thanks!

**Comment by 3noix** [comment]
It is a very good idea, I am gonna implement it.

And no, you are not missing anything, "description" is a non-static member function of AbstractRealJoystick class. If I am doing so, it is because I return the description that the DirectInput library provides me (using QtGameControllerModif).

I prefer the solution when we add a DESCRIPTION variable in the namespace (as you did above) compared to the static member function, because in the first one, the user includes only the information he needs to have access to and does not need to have access to the plugin class.

The third solution (using the non-static member function) is not usable only because I embedded the creation of the plugins classes into AbstractProfile and RealJoystickManager (in this commit https://github.com/3noix/UJPS/commit/d1c2370f225f3ae951161681f1ceef75b57ff434). And it is really much more simpler for the user like this.

**Comment by robert914** [comment]
Excellent! Yes, I agree that the DESCRIPTION variable in the namespace is probably easier / better to implement. It also highlights the base information you need from a new device -- you can just tell people to create the namespace header file as a submission for new joystick definitions (like I did) and they will know they need to also include the description string (like I didn't know initially). It might save you a step with users. :)

**Comment by 3noix** [comment]
Indeed. For most controllers I don't need anything more.

It can become harder if we want to support the LED or little LCD screens features that are available in some controllers... but I have already written a LED supports for Warthog throttle leds using Windows HID lib, so even for that I am quite confident... the problems should be "how to know how to format the data to send", and the issues to test it (not practical since the developer and the tester are 2 different people).

**Comment by robert914** [comment]
Right, the more complex stuff will take iteration with the owner of the device, of course. :-)

**Comment by 3noix** [comment]
I made the modification in the last commit.

I have also seen that I forgot the definition of buttons and axes for VirtualJoystick, so I did too. It will be necessary to do a few modifications in your profiles (I updated the examples profiles). I explained the modifications to do in the detailed part of the commit description, or you can just compare a profile with its previous version.

**Comment by robert914** [comment]
Excellent! I'll give this a try shortly.

One Question: If my vJoy device has < 128 buttons, will it be a problem that your vJoy device configuration specifies 128? What happens if my vJoy device has only 50 buttons, and I try to map to button 51? Is this an error / problem / ok?

**Comment by robert914** [comment]
Your updates are working great! Makes the profile much nicer / easier to code.

**Comment by 3noix** [comment]
In the last commit I provided the default value of 128 to VirtualJoystick constructor for the number of buttons. In fact, the number of buttons is only used to configure the vJoy device (if "use vJoyConfig.exe" is checked in the settings menu), but I do not recommend to use it. So in the case you use vJoyConfig separately, it is useless and you can remove it from Profile.cpp.

If you map a "vJoy button" whose index is greater than the number of buttons of the vJoy device, it just does nothing (no crash). In fact, the information is sent to vJoy but it does nothing. You can even use an index greater than 128, it will have no effect. I copied the function VirtualJoystick::setButton below (there are 4 32-bits integers to code the values of the 128 buttons)
```
// SET BUTTON /////////////////////////////////////////////////////////////////
bool VirtualJoystick::setButton(uint button, bool bPressed, RewriteOrNot ron)
{
	if (button >= 128 || m_buttonsLocked[button] || m_buttonsNoRewrite[button]) {return false;}
	if (ron == RewriteOrNot::NoRewrite) {m_buttonsNoRewrite[button] = true;}
	
	if (button < 32 && bPressed)        {m_report.lButtons    |=  bitLong(button);}
	else if (button < 32 && !bPressed)  {m_report.lButtons    &= ~bitLong(button);}
	else if (button < 64 && bPressed)   {m_report.lButtonsEx1 |=  bitLong(button%32);}
	else if (button < 64 && !bPressed)  {m_report.lButtonsEx1 &= ~bitLong(button%32);}
	else if (button < 96 && bPressed)   {m_report.lButtonsEx2 |=  bitLong(button%32);}
	else if (button < 96 && !bPressed)  {m_report.lButtonsEx2 &= ~bitLong(button%32);}
	else if (button < 128 && bPressed)  {m_report.lButtonsEx3 |=  bitLong(button%32);}
	else if (button < 128 && !bPressed) {m_report.lButtonsEx3 &= ~bitLong(button%32);}
	
	m_reportModified = true;
	return true;
}
```

**Comment by robert914** [comment]
So I don't need these lines at all?
```
	// virtual joystick(s) setup
	vj1 = new VirtualJoystick(1);
	emit message(VJOY::Description + " #1 configured.", Qt::blue);
	this->registerVirtualJoystick(vj1);
```

Or are you just saying I don't need to specify the number of buttons to "VirtualJoystick" as I've done above.

I thought I had to define my virtual joystick "vj1" for use in the mappings later. So I can't remove those lines, right?

**Comment by 3noix** [comment]
No, these lines are needed, you just "don't need to specify the number of buttons to "VirtualJoystick" as I've done above."

**Comment by robert914** [comment]
Perfect, thanks!
