### ISSUE TITLE
Question: How to properly map button to key for push and hold use

### ISSUE THREAD

**Issue by robert914** [3noix/UJPS#8]
Looking at the documentation, the only functions I can find for key mapping are the ActionKeyPress, ActionKeyRelease and ActionKeyPulse.

Basically, I want to map a particular button to a keyboard modifier such that when I hold the button down, the key is held down, and when the button is released, the key is released. I'm doing this to map a button to my push-to-talk key bindings for certain things.

I'm assuming I have to do it this way in my code:

```
	Map(xb1, ControlType::Button, XB360::SHOULDERL, AllLayers,
		new TriggerButtonPress{},
		new ActionKeyPress(Key_LAlt));
	Map(xb1, ControlType::Button, XB360::SHOULDERL, AllLayers,
		new TriggerButtonRelease{},
		new ActionKeyRelease(Key_LAlt));
```

There isn't a shorter way to write this, correct?  I realize if I leave off the "Release" mapping, the key is left down even after the button is released which isn't what I want for this case, but I can see the benefit of this in other situations. I don't have a problem doing the above, it makes perfect sense. I just want to make sure I'm not missing some shortcut way to do this.

Thanks!

**Comment by 3noix** [comment]
Ok, I am gonna add an ActionKeyChange so that it can be done in one line:
```
Map(xb1, ControlType::Button, XB360::SHOULDERL, AllLayers,
    new TriggerButtonChange{},
    new ActionKeyChange{Key_LAlt});
```

**Comment by 3noix** [comment]
I added ActionKeySetChange and ActionKeySetChangeOpposite. I tested them with this code:
```
Map(tmwj, ControlType::Button, TMWJ::H3L, AllLayers,
	new TriggerButtonChange{},
	new ActionKeySetChange{Key_A}
);
Map(tmwj, ControlType::Button, TMWJ::H3R, AllLayers,
	new TriggerButtonChange{},
	new ActionKeySetChangeOpposite{Key_B}
);
```

**Comment by robert914** [comment]
This is great! Works perfectly, thanks!!
